# Generated by Django 4.0.4 on 2022-05-04 19:14

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0002_actor_art_bts_collab_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='actor/'),
        ),
        migrations.AlterField(
            model_name='art',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='arts/'),
        ),
        migrations.AlterField(
            model_name='bts',
            name='file',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='bts/'),
        ),
        migrations.AlterField(
            model_name='collab',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='collabs/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='events/'),
        ),
    ]
