# Generated by Django 4.0.4 on 2022-06-06 20:57

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0005_rename_firstname_user_name_remove_user_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('picture', models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='poster/')),
            ],
        ),
        migrations.CreateModel(
            name='Soundtrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='soundtrack/')),
                ('file', models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='soundtrack/music/')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='summary',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='collab',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
