# Generated by Django 4.0.4 on 2022-09-13 15:47

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0007_remove_bot_answer_remove_bot_question_bot_answers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='X', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('picture', models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='crew/')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('picture', models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='poster/')),
                ('article', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
